// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uzvrvarehthhtedkhcem.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InV6dnJ2YXJlaHRoaHRlZGtoY2VtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU1MjE3NTksImV4cCI6MjA3MTA5Nzc1OX0.Wp2buCYX4vxVSlNneO2wQGwLVeemzK7MAQaM7qJTs3E";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});